#! /bin/sh

case "$1" in
    start)
        echo "Loading kernel module aesdchar"
        /bin/aesdchar_load 
        ;;
    stop)
        echo "Unloading kernel module aesdchar"
        /bin/aesdchar_unload 
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0

